"""交互表 update collect_count

Revision ID: 22bb67a51655
Revises: c9ae787f0659
Create Date: 2023-05-27 15:34:11.671744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22bb67a51655'
down_revision = 'c9ae787f0659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collect_count', sa.Integer(), nullable=True))
        batch_op.drop_column('is_favorite')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_favorite', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('collect_count')

    # ### end Alembic commands ###
