"""订单表 add  地址字段

Revision ID: c9ae787f0659
Revises: 4265f0b3dd87
Create Date: 2023-05-27 11:32:33.899100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9ae787f0659'
down_revision = '4265f0b3dd87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_constraint('collection_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('collection_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'recipe', ['recipe_id'], ['id'])

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=1000), nullable=True))
        batch_op.drop_constraint('order_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint('order_item_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('order_item_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order', ['order_id'], ['id'])
        batch_op.create_foreign_key(None, 'ingredient', ['ingredient_id'], ['id'])

    with op.batch_alter_table('roles_users', schema=None) as batch_op:
        batch_op.drop_constraint('roles_users_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('roles_users_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'])
        batch_op.create_foreign_key(None, 'admin', ['admin_id'], ['id'])

    with op.batch_alter_table('user_ingredient', schema=None) as batch_op:
        batch_op.drop_constraint('user_ingredient_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('user_ingredient_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'ingredient', ['ingredient_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_ingredient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_ingredient_ibfk_2', 'user', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('user_ingredient_ibfk_3', 'ingredient', ['ingredient_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('roles_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('roles_users_ibfk_2', 'admin', ['admin_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('roles_users_ibfk_1', 'role', ['role_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_item_ibfk_1', 'ingredient', ['ingredient_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('order_item_ibfk_2', 'order', ['order_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_ibfk_1', 'user', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.drop_column('address')

    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('collection_ibfk_2', 'user', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('collection_ibfk_1', 'recipe', ['recipe_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    # ### end Alembic commands ###
